# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'KeyriSupabase' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for KeyriSupabase
  pod 'keyri-pod'
  target 'KeyriSupabaseTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'KeyriSupabaseUITests' do
    # Pods for testing
  end

end
